server:
  servlet.context-path: /auth

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ...
            client-secret: ...
          google:
            client-id: ...
            client-secret: ...
  data:
    mongodb:
      database: auth
      host: localhost
      port: 27017

  thymeleaf:
    cache: false


auth:
  default-roles:
    - ROLE_USER
  account-validity-days: 3650

logging:
  level:
    org.springframework: DEBUG